### ISSUE TITLE
训练好的模型如何与top-K结合？

### ISSUE THREAD

**Issue by dongdongyu** [hwwang55/RippleNet#12]
![image](https://user-images.githubusercontent.com/17473874/58164922-53e7b980-7cb9-11e9-8e03-782ec3c00185.png)
文中你们提到分别与CTR和top-K结合了，想了解一下如何与top-k结合，希望指点下，谢谢您 @hwwang55

**Comment by chenyi729** [comment]
hi，你好，请问你的这个问题解决了么？

**Comment by hwwang55** [comment]
你好！top-k evaluation的代码在这里没有给出，但是在MKR的代码里面有（链接：https://github.com/hwwang55/MKR/blob/master/src/train.py），可以移植过来使用。谢谢！
