### ISSUE TITLE
你好，请教一下关于用户评分负样本的问题

### ISSUE THREAD

**Issue by yinpu** [hwwang55/RippleNet#18]
在preprocess.py其中convert_rating（）函数中  
当用户对项目评分大于阈值，作为为正样本。而随机选取用户未评分的项目，取为负样本。
我的问题是为何不取低于阈值的评分作为负样本，如果数量不够再随机选取未平分的项目。

**Comment by hwwang55** [comment]
你好！不这样做的原因是，user打低分的item也是他曾经看过的item，所以某种程度上也表明了该user对该item也有兴趣，所以拿这样的item做为负样本可能会对模型的学习造成影响。谢谢！

**Comment by paul0728** [comment]
作者您好,想请问一下,看程式码当中您的负样本是选取用户未评分的项目,取与正样本相同数量,所以这些负样本并未与用户有交互。但又为何在Table1 当中 #interactions 会将负样本数量也算进去呢?谢谢

**Comment by hwwang55** [comment]
您好，#interactions就是简单的表示数据集里training sample的数量。

**Comment by paul0728** [comment]
謝謝您！
