### ISSUE TITLE
Questions about the data files

### ISSUE THREAD

**Issue by harrywang** [hwwang55/RippleNet#19]
Hi Hongwei, thanks for the nice paper and the code. We have ported your code to TensorFlow 2.2.0 at https://github.com/tezignlab/RippleNet-TF2. I have a few questions about the data files and will try to use an example from the MovieLens dataset to be clear and more specific:

We found:

- a movie in the movie.dat: MovieID::Title::Genres, such as `356::Forrest Gump (1994)::Comedy|Romance|War`
- a user in the users.dat:  UserID::Gender::Age::Occupation::Zip-code, such as `10::F::35::1::95370`, user 10, female, 35 years old, academic/educator occupation, zip 95370.
- a movie rating: UserID::MovieID::Rating::Timestamp, such as `10::356::5::978226833`, user 10, rated Forrest Gump with 5 star

**Question 1**: `356` is the item id of Forrest Gump, which is mapped to satori id `231` in the `item_index2entity_id_rehashed` file, correct?

Then, we search satori id 231 in `kg_part1.txt` and `kg_part2.txt` files and got some related records shown below, which I think was from Microsoft Satori, such as the director of the film is id 49449 and one actor is 16680.

```
231	film.film.director	49449
85516	film.person_or_entity_appearing_in_film.film	231
49449	film.director.film	231
16680	film.actor.film	231
...
```

**Question 2**:  why two parts `kg_part1.txt` and `kg_part2.txt` for the movie dataset and only one part for the book dataset?

**Question 3**: how to find information about 49449 and 16680.? I mean the name of the director and actor? Satori does not seem to exist anymore.

Thanks a lot for your help!

Best,

Harry

**Comment by hwwang55** [comment]
Hi! Thanks for your interest in our work and thanks for implementing the model in TF2! Here are answers to your questions: 
1. Yes;
2. This is because Github limits the size of single uploaded file up to 100MB, if my memory is correct;
3. The original information of entities are anonymized due to the privacy policy of Microsoft. I'm sorry but I no longer have the access to Satori.

**Comment by harrywang** [comment]
Thanks a lot!
