### ISSUE TITLE
The Bing-News Dataset

### ISSUE THREAD

**Issue by LeeChenChen** [hwwang55/RippleNet#6]
Hi. Can you provide the Bing-News Dataset? Thanks a lot!

**Comment by hwwang55** [comment]
I'm sorry but I cannot provide the complete Bing-News dataset due to the Microsoft privacy policy. You can find a small version of Bing-News dataset here: https://github.com/hwwang55/DKN

**Comment by Yzx434904320** [comment]
Hi.Can you provide the processed Movielens and Book-Crossing data？Thanks a lot

**Comment by hwwang55** [comment]
Hi! The code for processing MovieLens and Book-Crossing can be found in this repository. Thanks!

**Comment by Yzx434904320** [comment]
Thanks for your reply, I want the embedding features used in wide&deep. the repository only provide the label.
