### ISSUE TITLE
Can you provide the actual semantics corresponding to each entity in KG?

### ISSUE THREAD

**Issue by yunyunandruirui** [hwwang55/RippleNet#7]
Hi，reading your paper has benefited a lot. In your dataset, the entity of the knowledge graph is represented by its id. I want to make a more intuitive analysis of the final result, so can you provide the actual semantics corresponding to each id?

**Comment by hwwang55** [comment]
Hi, thanks for your interest in our work. I'm sorry but I have left Microsoft and have no access to Satori again.
